name: Nightly
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  fuzz:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Fuzz / ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - uses: holepunchto/actions/restore-fuzz-corpus@v1
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: --debug --sanitize address --fuzz
      - run: bare-make test
      - uses: holepunchto/actions/save-fuzz-corpus@v1
        if: always()
